server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: identity_service
        uri: http://localhost:8080
        predicates:
          - Path=${app.api-prefix}/identity/**
        filters:
          - StripPrefix=2
      - id: profile_service
        uri: http://localhost:8081
        predicates:
          - Path=${app.api-prefix}/profile/users/**
        filters:
          - StripPrefix=2 #Loại bỏ 2 phần của path vd: cắt /api/v1 (vì thường sẽ thêm api vào để phân biệt FE và BE)