server:
  port: 8089
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3308/order_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true