server:
  port: 8090
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3308/product_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  services:
    file: http://localhost:8084